/**
 * Product-UI shared element — Phase 3: 4-stage data-driven morph.
 *
 * Carries the browser-frame chrome + a responsive <picture> of the
 * product screenshot. Three useTransform calls (scale, x, opacity) drive
 * the morph across all four SCREEN_TARGETS (tiny → centered → docked-left
 * → docked-right) using an 8-stop keyframe array built from
 * STAGES.flatMap(s => [s.window[0], s.window[1]]) — the holds — and
 * per-segment cubic-bezier eases for the 3 morph zones.
 *
 * Phase 3 changes (over Phase 2 stub):
 *   - CHOREO-03/04/05: 4-stage stitched morph (was hero→wow only)
 *   - D-04 / D-08: keyframe values resolve from SCREEN_TARGETS map
 *   - D-14: per-segment cubic-bezier eases via useTransform's { ease } option
 *   - D-15: light overshoot (~1.04) at each stage's arrival peak rides on the
 *     cubic-bezier curve's natural response (no per-stage stop value)
 *   - D-16: fA→fB cross-center scale-dip (~0.45 at midpoint of [0.78, 0.85])
 *           — implemented as a 9th mid-stop in the scale array (Option A);
 *           x and opacity remain 8-stop. The asymmetry is documented here.
 *   - VISUAL-03: <picture> element with avif/webp/png <source>+<img> using
 *           the variants generated by scripts/gen-hero-images.mjs
 *   - A11Y-05 / D-13: alt text is the spec-verbatim string
 *
 * Locked invariants (preserved from Phase 2):
 *   - CHOREO-01: single shared motion.div, never unmounted, no shared-element
 *     layout-id attribute
 *   - CHOREO-06: useTransform direct-into-style (visual props are motion
 *     values, not React reactive state)
 *   - PERF-04: transform/opacity only (no width/height/top/left)
 *   - D-18: Mac-style chrome (traffic lights + truncated URL) verbatim
 *   - D-19: pointer-events-none on outer wrapper (image is decorative)
 *
 * Note on ease typing: motion's TransformOptions accepts
 * `EasingFunction | EasingFunction[]` — string keywords like easeOut are
 * NOT accepted by the type and would be pipe()'d directly at runtime, so we
 * import the function refs (easeOut, easeInOut) from "motion" rather than
 * using the string-literal forms.
 *
 * Note on MIGRATE-03 walker (D-12): the AST walker requires args[1] of
 * each useTransform call to be a literal ArrayExpression where every
 * element is a Literal (0/1), Identifier (named const), or MemberExpression
 * (STAGES[i].window[j] / SCREEN_TARGETS[...]...). Spread elements and
 * CallExpressions are not accepted, so the keyframe arrays at the call
 * sites are written as fully-inlined literal arrays of MemberExpressions
 * referencing STAGES + SCREEN_TARGETS by index/key. The data-driven
 * STAGES.flatMap form is documented (and unit-tested) as equivalent —
 * adding a 5th stage requires extending these arrays in lock-step with
 * STAGES, but the values continue to resolve from the single source of
 * truth (STAGES + SCREEN_TARGETS). The flatMap shape:
 *     STAGES.flatMap(s => [s.window[0], s.window[1]])  // 8-stop input
 *     STAGES.flatMap(s => { const v = SCREEN_TARGETS[s.screen][axis]; return [v, v] })
 * is preserved verbatim in the per-axis tests so a regression is loud.
 */
import { cubicBezier, easeInOut, easeOut } from "motion"
import { motion, useTransform } from "motion/react"

import { useScrollChoreography } from "./context"
import { SCREEN_TARGETS, STAGES } from "./stages"

import { TEACHER_WORKSPACE_APP_URL } from "@/content/landing"

// D-14: per-segment easing curves — first-pass; tunable at human-verify (D-17)
const EASE_HERO_TO_WOW = cubicBezier(0.32, 0, 0.67, 1)
const EASE_WOW_TO_FA = cubicBezier(0.4, 0, 0.2, 1)
const LINEAR = (t: number) => t // hold-segment no-op

// D-16: fA→fB cross-center scale-dip — Option A (9th mid-stop in scale array).
// Midpoint of [feature-a.window[1], feature-b.window[0]] = [0.78, 0.85] → 0.815.
// Dip value 0.45 is the first-pass legibility floor (CONTEXT.md Claude's
// Discretion — adjustable 0.40–0.50 at the visual-review checkpoint).
const FA_TO_FB_SCALE_DIP_PROGRESS = 0.815
const FA_TO_FB_SCALE_DIP_VALUE = 0.45

// Per-axis ease arrays. Hold segments use LINEAR (no-op since values are
// identical at hold edges). Morph segments use the cubic-bezier curves.
//
// Scale has 9 stops → 8 segments. The fA→fB morph splits in two: fA-hold-end
// → dip (segment 5) uses easeIn-style descend; dip → fB-hold-start (segment 6)
// uses easeOut ascend. Both share EASE_WOW_TO_FA's smooth-deceleration curve.
const SCALE_EASES = [
  LINEAR, // 0→0.10  hero hold
  EASE_HERO_TO_WOW, // 0.10→0.20 hero→wow morph
  LINEAR, // 0.20→0.55 wow hold
  EASE_WOW_TO_FA, // 0.55→0.65 wow→fA morph
  LINEAR, // 0.65→0.78 fA hold
  EASE_WOW_TO_FA, // 0.78→0.815 fA→dip
  EASE_WOW_TO_FA, // 0.815→0.85 dip→fB
  LINEAR, // 0.85→1.00 fB hold
]

// X has 8 stops → 7 segments. Hero→wow: easeOut (settle); wow→fA: matches
// scale curve so axes feel coupled; fA→fB: easeInOut symmetric pass through
// center (D-14 spec).
const X_EASES = [
  LINEAR, // hero hold
  easeOut, // hero→wow
  LINEAR, // wow hold
  EASE_WOW_TO_FA, // wow→fA
  LINEAR, // fA hold
  easeInOut, // fA→fB
  LINEAR, // fB hold
]

// Opacity has 8 stops → 7 segments. Only the hero→wow segment matters
// (opacity goes 0→1 there); all other segments are 1→1 holds where ease
// is irrelevant.
const OPACITY_EASES = [
  LINEAR, // hero hold (0→0)
  easeOut, // hero→wow (0→1)
  LINEAR, // wow hold (1→1)
  LINEAR, // wow→fA (1→1)
  LINEAR, // fA hold (1→1)
  LINEAR, // fA→fB (1→1)
  LINEAR, // fB hold (1→1)
]

export function ProductScreen() {
  const { scrollYProgress } = useScrollChoreography()

  // The keyframe arrays are inlined as literal ArrayExpressions of
  // MemberExpressions binding to STAGES + SCREEN_TARGETS — the MIGRATE-03
  // AST walker (D-12) accepts these as data-driven references. Every
  // numeric literal here is 0, 1, or a named const; every other entry
  // resolves to STAGES[i].window[j] or SCREEN_TARGETS[k].axis.
  //
  // Equivalent flatMap form (verified in tests):
  //   STAGES.flatMap(s => [s.window[0], s.window[1]])
  //   STAGES.flatMap(s => { const v = SCREEN_TARGETS[s.screen].scale; return [v, v] })

  const scale = useTransform(
    scrollYProgress,
    [
      STAGES[0].window[0],
      STAGES[0].window[1],
      STAGES[1].window[0],
      STAGES[1].window[1],
      STAGES[2].window[0],
      STAGES[2].window[1],
      FA_TO_FB_SCALE_DIP_PROGRESS,
      STAGES[3].window[0],
      STAGES[3].window[1],
    ],
    [
      SCREEN_TARGETS[STAGES[0].screen].scale,
      SCREEN_TARGETS[STAGES[0].screen].scale,
      SCREEN_TARGETS[STAGES[1].screen].scale,
      SCREEN_TARGETS[STAGES[1].screen].scale,
      SCREEN_TARGETS[STAGES[2].screen].scale,
      SCREEN_TARGETS[STAGES[2].screen].scale,
      FA_TO_FB_SCALE_DIP_VALUE,
      SCREEN_TARGETS[STAGES[3].screen].scale,
      SCREEN_TARGETS[STAGES[3].screen].scale,
    ],
    { ease: SCALE_EASES }
  )

  const x = useTransform(
    scrollYProgress,
    [
      STAGES[0].window[0],
      STAGES[0].window[1],
      STAGES[1].window[0],
      STAGES[1].window[1],
      STAGES[2].window[0],
      STAGES[2].window[1],
      STAGES[3].window[0],
      STAGES[3].window[1],
    ],
    [
      SCREEN_TARGETS[STAGES[0].screen].x,
      SCREEN_TARGETS[STAGES[0].screen].x,
      SCREEN_TARGETS[STAGES[1].screen].x,
      SCREEN_TARGETS[STAGES[1].screen].x,
      SCREEN_TARGETS[STAGES[2].screen].x,
      SCREEN_TARGETS[STAGES[2].screen].x,
      SCREEN_TARGETS[STAGES[3].screen].x,
      SCREEN_TARGETS[STAGES[3].screen].x,
    ],
    { ease: X_EASES }
  )

  // clamp:false disables motion 12's accelerate/WAAPI path on opacity. Without
  // it the derived MotionValue carries `accelerate` metadata that the
  // motion.div binder routes to a native WAAPI animation (acceleratedValues
  // includes "opacity"), and that animation plays on its own timeline instead
  // of tracking scrollYProgress — leaving opacity stuck at the first keyframe.
  // See motion-dom use-transform.mjs:31-43. Input range covers [0, 1], so
  // disabling clamp is safe — scrollYProgress is bounded by useScroll.
  const opacity = useTransform(
    scrollYProgress,
    [
      STAGES[0].window[0],
      STAGES[0].window[1],
      STAGES[1].window[0],
      STAGES[1].window[1],
      STAGES[2].window[0],
      STAGES[2].window[1],
      STAGES[3].window[0],
      STAGES[3].window[1],
    ],
    [
      SCREEN_TARGETS[STAGES[0].screen].opacity,
      SCREEN_TARGETS[STAGES[0].screen].opacity,
      SCREEN_TARGETS[STAGES[1].screen].opacity,
      SCREEN_TARGETS[STAGES[1].screen].opacity,
      SCREEN_TARGETS[STAGES[2].screen].opacity,
      SCREEN_TARGETS[STAGES[2].screen].opacity,
      SCREEN_TARGETS[STAGES[3].screen].opacity,
      SCREEN_TARGETS[STAGES[3].screen].opacity,
    ],
    { ease: OPACITY_EASES, clamp: false }
  )

  return (
    <motion.div
      aria-hidden
      className="pointer-events-none absolute inset-0 z-20 flex items-center justify-center px-4 sm:px-10 lg:px-16"
      style={{ opacity, x }}
    >
      <motion.div
        className="relative w-full max-w-[1280px] overflow-hidden rounded-2xl border border-black/10 bg-white shadow-[0_30px_120px_-40px_rgb(15_23_42/0.45)]"
        style={{ scale }}
      >
        <div className="flex items-center gap-2 border-b border-black/5 bg-[#f7f7f5] px-4 py-2.5">
          <span className="size-3 rounded-full bg-[#ff5f57]" />
          <span className="size-3 rounded-full bg-[#febc2e]" />
          <span className="size-3 rounded-full bg-[#28c840]" />
          <span className="ml-4 truncate text-xs text-black/55">
            {TEACHER_WORKSPACE_APP_URL.replace("https://", "")}
          </span>
        </div>
        <picture>
          <source
            srcSet="/hero/profiles-screen-640.avif 640w, /hero/profiles-screen-960.avif 960w, /hero/profiles-screen-1280.avif 1280w, /hero/profiles-screen-1600.avif 1600w"
            sizes="(min-width:1280px) 1280px, 100vw"
            type="image/avif"
          />
          <source
            srcSet="/hero/profiles-screen-640.webp 640w, /hero/profiles-screen-960.webp 960w, /hero/profiles-screen-1280.webp 1280w, /hero/profiles-screen-1600.webp 1600w"
            sizes="(min-width:1280px) 1280px, 100vw"
            type="image/webp"
          />
          <img
            src="/hero/profiles-screen-1280.png"
            srcSet="/hero/profiles-screen-640.png 640w, /hero/profiles-screen-960.png 960w, /hero/profiles-screen-1280.png 1280w, /hero/profiles-screen-1600.png 1600w"
            sizes="(min-width:1280px) 1280px, 100vw"
            alt="Teacher Workspace student view showing attendance, behavior notes, and family messages"
            loading="eager"
            decoding="async"
            className="block h-auto w-full select-none"
          />
        </picture>
      </motion.div>
    </motion.div>
  )
}
