/**
 * Product-UI shared element — 3-stage data-driven morph.
 *
 * Carries the browser-frame chrome + a responsive <picture> of the
 * product screenshot. Three useTransform calls (scale, x, opacity) drive
 * the morph across the three stages (hero → wow → docked) using a 6-stop
 * keyframe array built from
 * STAGES.flatMap(s => [s.window[0], s.window[1]]) — the holds — and
 * per-segment cubic-bezier eases for the 2 morph zones.
 *
 *   - Keyframe values resolve from each stage's inlined rect fields
 *     (scale / x / y / opacity), no preset-target indirection.
 *   - D-14: per-segment cubic-bezier eases via useTransform's { ease } option
 *   - D-15: light overshoot (~1.04) at each stage's arrival peak rides on the
 *     cubic-bezier curve's natural response (no per-stage stop value)
 *   - VISUAL-03: <picture> element with avif/webp/png <source>+<img> using
 *           the variants generated by scripts/gen-hero-images.mjs
 *   - A11Y-05 / D-13: alt text is the spec-verbatim string
 *
 * Locked invariants:
 *   - CHOREO-01: single shared motion.div, never unmounted, no shared-element
 *     layout-id attribute
 *   - CHOREO-06: useTransform direct-into-style (visual props are motion
 *     values, not React reactive state)
 *   - PERF-04: transform/opacity only (no width/height/top/left)
 *   - D-18: Mac-style chrome (traffic lights + truncated URL) verbatim
 *   - D-19: pointer-events-none on outer wrapper (image is decorative)
 *
 * Note on ease typing: motion's TransformOptions accepts
 * `EasingFunction | EasingFunction[]` — string keywords like easeOut are
 * NOT accepted by the type and would be pipe()'d directly at runtime, so we
 * import the function ref (easeOut) from "motion" rather than using the
 * string-literal form.
 */
import { cubicBezier, easeOut } from "motion"
import { motion, useTransform } from "motion/react"

import { useScrollChoreography } from "./context"
import { useFlowStages } from "./dev-flow-context"

import { TEACHER_WORKSPACE_APP_URL } from "@/content/landing"

// D-14: per-segment easing curves — first-pass; tunable at human-verify (D-17)
const EASE_HERO_TO_WOW = cubicBezier(0.32, 0, 0.67, 1)
const EASE_WOW_TO_DOCKED = cubicBezier(0.4, 0, 0.2, 1)
const LINEAR = (t: number) => t // hold-segment no-op

// Per-axis ease arrays. 6 stops → 5 segments. Hold segments use LINEAR
// (no-op since values are identical at hold edges). Morph segments use
// the cubic-bezier curves.
const SCALE_EASES = [
  LINEAR, // hero hold
  EASE_HERO_TO_WOW, // hero→wow morph
  LINEAR, // wow hold
  EASE_WOW_TO_DOCKED, // wow→docked morph
  LINEAR, // docked hold
]

// Hero→wow: easeOut (settle); wow→docked: matches scale curve so axes feel
// coupled.
const X_EASES = [
  LINEAR, // hero hold
  easeOut, // hero→wow
  LINEAR, // wow hold
  EASE_WOW_TO_DOCKED, // wow→docked
  LINEAR, // docked hold
]

// Only the hero→wow segment matters for opacity (it goes 0→1 there if any
// stage opts out of opacity 1; today all stages = 1, so all segments are holds).
const OPACITY_EASES = [
  LINEAR, // hero hold
  easeOut, // hero→wow
  LINEAR, // wow hold
  LINEAR, // wow→docked
  LINEAR, // docked hold
]

/**
 * Vertical offset of paper-card's transform-origin from its own center,
 * in viewport-height percent. Paper-backdrop sets `transformOrigin:
 * "50% 92%"`, so the origin is 42% of paper-card's height BELOW the
 * paper-card's center. As the paper-card scales by Sp, its content-area's
 * vertical center drifts UP by `42 * (Sp - 1)` vh in viewport coords —
 * `compensatedY` re-anchors the bundled child to compensate.
 *
 * Baked as a constant rather than parsed from PaperBackdrop's CSS to keep
 * the math local. If the paper-card's transform-origin ever changes, this
 * constant must change in lock-step.
 */
const PAPER_CARD_ORIGIN_Y_OFFSET_VH = 42

/**
 * Parse a CSS length string ("+28vw", "-2.2vw", "0", "+23vh") to a number.
 * Returns 0 for "0" (no unit) and parses through the leading sign.
 * Doesn't validate the unit — the caller knows the axis (vw vs vh).
 */
function parseCssLength(value: string): number {
  const match = value.match(/^([+-]?\d+(?:\.\d+)?)/)
  return match ? parseFloat(match[1]) : 0
}

/**
 * Divide a CSS length string ("+28vw", "-2.2vw", "0") by a numeric
 * scale factor and re-stringify, preserving the unit. Used for x
 * compensation (paper-card's transform-origin x = 50%, so x has no
 * origin-shift component — purely multiplicative).
 */
function divideCssLength(value: string, scale: number): string {
  if (scale === 0 || !Number.isFinite(scale)) return value
  const match = value.match(/^([+-]?\d+(?:\.\d+)?)([a-z%]*)$/i)
  if (!match) return value
  const num = parseFloat(match[1])
  const unit = match[2]
  if (num === 0) return "0"
  const compensated = num / scale
  const rounded = Math.round(compensated * 10000) / 10000
  return `${rounded}${unit}`
}

/**
 * Compensate a vh-based child translate for both paper-card scale AND
 * its off-center transform-origin (50%, 92%). Derivation:
 *
 *   parent scales by Sp around origin at (50%, 92%) of its bounding box.
 *   the parent's content-area center maps to viewport-y =
 *     92 + (50 - 92) * Sp = 92 - 42*Sp
 *   so a child at parent-local center (with no translate) ends up at
 *     viewport-y = 92 - 42*Sp vh   (NOT 50vh as ideal!)
 *
 *   to land at viewport-y = 50 + yRect (the rect's intent), the child
 *   needs translate ty such that
 *     92 + (50 + ty - 92) * Sp = 50 + yRect
 *   solving:
 *     ty = 42*(1 - 1/Sp) + yRect/Sp
 *
 * At Sp = 1 the first term is 0 and the second reduces to yRect, so
 * compensation is a no-op during the hero hold (and outside the
 * orchestrator).
 */
function compensateYTranslate(yStr: string, scale: number): string {
  if (scale === 0 || !Number.isFinite(scale)) return yStr
  const yVh = parseCssLength(yStr)
  const tyVh =
    PAPER_CARD_ORIGIN_Y_OFFSET_VH * (1 - 1 / scale) + yVh / scale
  const rounded = Math.round(tyVh * 10000) / 10000
  return `${rounded}vh`
}

export function ProductScreen() {
  const { scrollYProgress, paperCardScale } = useScrollChoreography()
  // Reads live overrides from <DevFlowPanel> when mounted; falls back to
  // compile-time STAGES outside dev. Keyframes re-derive on each render so
  // visual changes are visible the same frame in dev tuning.
  const STAGES = useFlowStages()

  // 6-stop keyframe array: STAGES.flatMap(s => [s.window[0], s.window[1]]).
  // Inlined as a literal MemberExpression array so the structure is grep-able
  // and adding a 4th stage requires extending each array in lock-step.

  const scale = useTransform(
    scrollYProgress,
    [
      STAGES[0].window[0],
      STAGES[0].window[1],
      STAGES[1].window[0],
      STAGES[1].window[1],
      STAGES[2].window[0],
      STAGES[2].window[1],
    ],
    [
      STAGES[0].scale,
      STAGES[0].scale,
      STAGES[1].scale,
      STAGES[1].scale,
      STAGES[2].scale,
      STAGES[2].scale,
    ],
    { ease: SCALE_EASES }
  )

  const x = useTransform(
    scrollYProgress,
    [
      STAGES[0].window[0],
      STAGES[0].window[1],
      STAGES[1].window[0],
      STAGES[1].window[1],
      STAGES[2].window[0],
      STAGES[2].window[1],
    ],
    [
      STAGES[0].x,
      STAGES[0].x,
      STAGES[1].x,
      STAGES[1].x,
      STAGES[2].x,
      STAGES[2].x,
    ],
    { ease: X_EASES }
  )

  // y mirrors the x channel — non-zero only on hero so the screen overlays
  // the laptop in the cartoon illustration during hero stage.
  const y = useTransform(
    scrollYProgress,
    [
      STAGES[0].window[0],
      STAGES[0].window[1],
      STAGES[1].window[0],
      STAGES[1].window[1],
      STAGES[2].window[0],
      STAGES[2].window[1],
    ],
    [
      STAGES[0].y,
      STAGES[0].y,
      STAGES[1].y,
      STAGES[1].y,
      STAGES[2].y,
      STAGES[2].y,
    ],
    { ease: X_EASES }
  )

  // clamp:false disables motion 12's accelerate/WAAPI path on opacity. Without
  // it the derived MotionValue carries `accelerate` metadata that the
  // motion.div binder routes to a native WAAPI animation (acceleratedValues
  // includes "opacity"), and that animation plays on its own timeline instead
  // of tracking scrollYProgress — leaving opacity stuck at the first keyframe.
  // See motion-dom use-transform.mjs:31-43. Input range covers [0, 1], so
  // disabling clamp is safe — scrollYProgress is bounded by useScroll.
  const opacity = useTransform(
    scrollYProgress,
    [
      STAGES[0].window[0],
      STAGES[0].window[1],
      STAGES[1].window[0],
      STAGES[1].window[1],
      STAGES[2].window[0],
      STAGES[2].window[1],
    ],
    [
      STAGES[0].opacity,
      STAGES[0].opacity,
      STAGES[1].opacity,
      STAGES[1].opacity,
      STAGES[2].opacity,
      STAGES[2].opacity,
    ],
    { ease: OPACITY_EASES, clamp: false }
  )

  // Bundled-into-paper-card compensation. The outer paper-card's scale
  // multiplies through to this child's transform space, so we divide each
  // visual property by `paperCardScale` and the rendered transform reads
  // as the rect's intrinsic value. With paperCardScale = 1 (hero hold,
  // and outside the orchestrator) compensation is a no-op.
  //
  // We trigger the compensation off `scrollYProgress` and read the other
  // motion values via `.get()` to avoid motion's homogeneous-typed
  // multi-input overload (it doesn't model mixed [string, number] tuples).
  // This is safe because scale, x, y, and paperCardScale are all
  // derivatives of scrollYProgress — motion fires derivatives in
  // creation order in the same frame, so by the time the compensated
  // value's transformer runs, all upstream `.get()` calls return the
  // latest frame's values.
  const compensatedScale = useTransform(scrollYProgress, () => {
    const s = scale.get()
    const ps = paperCardScale.get()
    return ps === 0 ? s : s / ps
  })
  const compensatedX = useTransform(scrollYProgress, () =>
    divideCssLength(x.get(), paperCardScale.get())
  )
  const compensatedY = useTransform(scrollYProgress, () =>
    compensateYTranslate(y.get(), paperCardScale.get())
  )

  return (
    <motion.div
      aria-hidden
      className="pointer-events-none absolute inset-0 z-20 flex items-center justify-center px-4 sm:px-10 lg:px-16"
      style={{ opacity, x: compensatedX, y: compensatedY }}
    >
      <motion.div
        className="relative w-full max-w-[1280px] overflow-hidden rounded-2xl border border-black/10 bg-white shadow-[0_30px_120px_-40px_rgb(15_23_42/0.45)]"
        style={{ scale: compensatedScale }}
      >
        <div className="flex items-center gap-2 border-b border-black/5 bg-[#f7f7f5] px-4 py-2.5">
          <span className="size-3 rounded-full bg-[#ff5f57]" />
          <span className="size-3 rounded-full bg-[#febc2e]" />
          <span className="size-3 rounded-full bg-[#28c840]" />
          <span className="ml-4 truncate text-xs text-black/55">
            {TEACHER_WORKSPACE_APP_URL.replace("https://", "")}
          </span>
        </div>
        <picture>
          <source
            srcSet="/hero/profiles-screen-640.avif 640w, /hero/profiles-screen-960.avif 960w, /hero/profiles-screen-1280.avif 1280w, /hero/profiles-screen-1600.avif 1600w"
            sizes="(min-width:1280px) 1280px, 100vw"
            type="image/avif"
          />
          <source
            srcSet="/hero/profiles-screen-640.webp 640w, /hero/profiles-screen-960.webp 960w, /hero/profiles-screen-1280.webp 1280w, /hero/profiles-screen-1600.webp 1600w"
            sizes="(min-width:1280px) 1280px, 100vw"
            type="image/webp"
          />
          <img
            src="/hero/profiles-screen-1280.png"
            srcSet="/hero/profiles-screen-640.png 640w, /hero/profiles-screen-960.png 960w, /hero/profiles-screen-1280.png 1280w, /hero/profiles-screen-1600.png 1600w"
            sizes="(min-width:1280px) 1280px, 100vw"
            alt="Teacher Workspace student view showing attendance, behavior notes, and family messages"
            loading="eager"
            decoding="async"
            className="block h-auto w-full select-none"
          />
        </picture>
      </motion.div>
    </motion.div>
  )
}
